# Generated by Django 4.0.4 on 2022-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Super Blog!!!', max_length=255),
        ),
    ]
